### ISSUE TITLE
Add Menu Tool For Mantra to RenderMan

### ISSUE THREAD

**Issue by riujefus** [SideswipeeZ/houdini-shader-converter#1]
Nice tool. Added a menu for shaders to convert from Mantra to Renderman as well. Thank You.

**Comment by SideswipeeZ** [comment]
> 

Hi, Do you have a examplar Shader you can can provide? I have never used renderman so Im not sure how the shaders are constructed. If they work the same as arnold/rs/octane etc then I can add them to this tool no problem.

**Comment by riujefus** [comment]
Hello, Thank you for your response. I truly appreciate your willingness to integrate RenderMan into the Shader conversion tool you're developing.

I understand that explaining Shader construction in words can be simpler than using screenshots. Therefore, here's a brief description of the Shader construction I use in RenderMan:

Diffuse Shader, Specular Shader, Bump Map,

I realize that these concepts might not be entirely clear without a visual demonstration. As such, I invite you to run RenderMan and attempt to construct the aforementioned Shaders firsthand. This way, you can directly observe the required structure and settings within RenderMan.
